version: '3.8'

services:
  frontend:
    build:
      context: ./swahili-scribe-frontend-main
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Sema-ASR
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    mem_limit: 4g
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./Sema-ASR:/app
      - model_cache:/root/.cache/huggingface/hub
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  model_cache:
